laserOdometry:
  ioRatio: 2
  maxIterations: 25
  minLastCornerCloudSize: 10
  minLastSurfaceCloudSize: 100
  maxPointSearchSqDis: 10
  minPointSelNum: 10

laserMapping:
  maxIterations: 10
  mapFrameNum: 5
  cornerFilterSize: 0.2
  surfaceFilterSize: 0.4
  cubeSize: 250.0
  laserCloudCenWidth: 10
  laserCloudCenHeight: 5
  laserCloudCenDepth: 10

